### PR TITLE
[W-8857319] SFDX conversion and dataset updates

### PR DESCRIPTION
**Pull request by davidmreed**
This PR captures maintenance work done for a demo, including converting Outbound Funds to SFDX format and updating the dataset and mapping file.

# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by spelak-salesforce** [comment]
@davidmreed , FYI: Orion will is planning on merging this PR this sprint.   We are in progress creating a child branch to fix the `Label Audit` errors.   We will dev-review this PR, and we will need a RelEng review after merging our Label Audit fix.

**Comment by spelak-salesforce** [comment]
[W-8857319](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B00000095wvHIAQ/view)

**Comment by spelak-salesforce** [comment]
@davidmreed , can you give this a look over before we start reviewing.   Also, can we get a code owner review by @SalesforceFoundation/release-engineering-reviewers ?   Devs will start reviewing.

**Comment by davidmreed** [comment]
@spelak-salesforce  I created this PR but I think it's ready to go. @jstvz will have to approve it for CODEOWNERS since I cannot.

**Review by jstvz — COMMENTED** [review]
CODEOWNERS 🆗

**Review by jstvz — APPROVED** [review]

**Review by scottwarren-sfdo — APPROVED** [review]

**Pull request merged**
