### PR TITLE
Refactor installer flow to be locally runnable

### PR DESCRIPTION
**Pull request by davidmreed**
This PR modifies Outbound Funds' installer flow to be runnable locally as the `customer_org` flow. It also adds a flow `install_npsp` to support NPSP installation in that context. The installer now automatically resolves the latest NPSP Extension version rather than hard-coding a version number.

# Critical Changes

# Changes

# Issues Closed

### CODE REVIEW

**Comment by davidmreed** [comment]
Staging installer for review: https://metadeploy-stg.herokuapp.com/products/outbound-funds/d1a8972f1d490115e8f574bb4c984e19796cc2f7

**Comment by spelak-salesforce** [comment]
GUS: [W-7827333](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008WFqCIAW/view)

**Comment by spelak-salesforce** [comment]
@SalesforceFoundation/release-engineering-reviewers , this needs CODEOWNER review.

**Comment by gaganpsandhu** [comment]
Tested an installer for an org with npsp and without npsp and installation ran successfully.

**Pull request merged**
